# Generated by Django 3.2.4 on 2021-10-01 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='placements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=80)),
                ('cmpname', models.CharField(max_length=80)),
                ('cmplogo', models.ImageField(default='', upload_to='static/placement')),
                ('city', models.CharField(max_length=100)),
                ('pyear', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('stupic', models.ImageField(default='', upload_to='static/studentpic/')),
                ('pdate', models.DateField()),
                ('pcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.courses')),
            ],
        ),
    ]
