# Generated by Django 3.2.4 on 2022-05-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_faculty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='placements',
            new_name='admission',
        ),
        migrations.RenameModel(
            old_name='recuiters',
            new_name='notification',
        ),
    ]
